import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import avatar1 from '../public/assets/avatar1.jpeg'
import avatar2 from '../public/assets/avatar2.png'
import avatar3 from '../public/assets/avatar3.jpeg'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Gabriel Nasheed Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className='bg-white px-10 '
      >
        <section
          className='min-h-screen'
        >
          <nav
            className='py-10 mb-12 flex justify-between'
          >
            <h1
              className='text-xl'
            >DevelopedbyGabs</h1>
            <ul
              className='flex items-center'
            >
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' /></li>
              <li><a href="#" className='bg-gradient-to-r from-teal-500 to-teal-700 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Gabriel Nasheed</h2>
            <h3 className='text-2xl py-2'>Developer and Translator</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa itaque numquam doloribus.
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veniam quod dolorem?
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 font-medium'>
            <AiFillGithub />
            <AiFillLinkedin />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={avatar2} alt="myself Gabriel Nasheed" layout='fill' objectFit='cover'/>
          </div>
        </section>

        <section>
          <div>
            <h3>Service I offer</h3>
          </div>
        </section>

      </main>

    </div>
  )
}
